In [2]:
import numpy as np

#### 1-D array

In [3]:
list1 =[12,34,56,56]

In [5]:
arr1d = np.array(list1)

In [6]:
type(arr1d)

numpy.ndarray

In [7]:
arr1d

array([12, 34, 56, 56])

In [8]:
list1.append(55)

In [9]:
list1

[12, 34, 56, 56, 55]

In [11]:
arr1d +30  #here can possible to add the values.

array([42, 64, 86, 86])

In [10]:
list +2 #concatanation can't done with the int .It can be possoble by using one more list.

TypeError: unsupported operand type(s) for +: 'type' and 'int'

#### 2-D array.

In [13]:
list2 = [[23,34,45,67,34],[12,78,75,90,33]]
array = np.array(list2)
print(array)

[[23 34 45 67 34]
 [12 78 75 90 33]]


In [15]:
type(array)

numpy.ndarray

In [17]:
array.dtype

dtype('int32')

In [18]:
array2d = np.array(list2,dtype=float)
print(array2d)

[[23. 34. 45. 67. 34.]
 [12. 78. 75. 90. 33.]]


In [19]:
array2d.astype(int)

array([[23, 34, 45, 67, 34],
       [12, 78, 75, 90, 33]])

In [20]:
array2d.astype(str)

array([['23.0', '34.0', '45.0', '67.0', '34.0'],
       ['12.0', '78.0', '75.0', '90.0', '33.0']], dtype='<U32')

In [21]:
array2d.tostring()  #it converted to the byte string

b'\x00\x00\x00\x00\x00\x007@\x00\x00\x00\x00\x00\x00A@\x00\x00\x00\x00\x00\x80F@\x00\x00\x00\x00\x00\xc0P@\x00\x00\x00\x00\x00\x00A@\x00\x00\x00\x00\x00\x00(@\x00\x00\x00\x00\x00\x80S@\x00\x00\x00\x00\x00\xc0R@\x00\x00\x00\x00\x00\x80V@\x00\x00\x00\x00\x00\x80@@'

In [22]:
array2d.tobytes()

b'\x00\x00\x00\x00\x00\x007@\x00\x00\x00\x00\x00\x00A@\x00\x00\x00\x00\x00\x80F@\x00\x00\x00\x00\x00\xc0P@\x00\x00\x00\x00\x00\x00A@\x00\x00\x00\x00\x00\x00(@\x00\x00\x00\x00\x00\x80S@\x00\x00\x00\x00\x00\xc0R@\x00\x00\x00\x00\x00\x80V@\x00\x00\x00\x00\x00\x80@@'

#### Dtype and Shape.

In [23]:
array2d.astype(float)

array([[23., 34., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [24]:
array2d

array([[23., 34., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [25]:
print('Shape :',array2d.shape)

Shape : (2, 5)


In [26]:
print('Size :',array2d.size)

Size : 10


In [27]:
array2d.dtype

dtype('float64')

In [29]:
arr1d.ndim

1

In [30]:
array2d.ndim

2

In [31]:
array3 = array2d*array2d

In [32]:
print(array3)

[[ 529. 1156. 2025. 4489. 1156.]
 [ 144. 6084. 5625. 8100. 1089.]]


In [33]:
array2d[0]

array([23., 34., 45., 67., 34.])

In [34]:
array2d[1]

array([12., 78., 75., 90., 33.])

In [35]:
arr1d[1]

34

In [36]:
array2d[0][0]  #[row][col]

23.0

#### Bool array

In [39]:
boolarray= array2d>30
boolarray

array([[False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [44]:
array2d[boolarray] #return the true vallues.

array([34., 45., 67., 34., 78., 75., 90., 33.])

In [46]:
array2d[:,:-1 ]

array([[23., 34., 45., 67.],
       [12., 78., 75., 90.]])

In [47]:
array2d

array([[23., 34., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [48]:
array2d[::-1,::-1]

array([[33., 90., 75., 78., 12.],
       [34., 67., 45., 34., 23.]])

#### np.nan and np.inf

In [50]:
np.nan  #not a number

nan

In [51]:
np.inf #infinite can't define.

inf

In [53]:
array2d

array([[23., 34., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [54]:
array2d[0][0]=np.nan
array2d[0][1]=np.inf
array2d

array([[nan, inf, 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [55]:
np.isnan(array2d)

array([[ True, False, False, False, False],
       [False, False, False, False, False]])

In [56]:
np.isinf(array2d)

array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [57]:
missing_flag = np.isnan(array2d)|np.isinf(array2d)
missing_flag

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [58]:
#replace the inf and nan with 0.

In [59]:
array2d[missing_flag]

array([nan, inf])

In [60]:
array2d[missing_flag] =0

In [61]:
array2d

array([[ 0.,  0., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

#### Stastical operation.

In [62]:
array2d.mean()

43.4

In [64]:
array2d.max()

90.0

In [65]:
array2d.min()

0.0

In [66]:
array2d.std()

31.426740206391116

In [67]:
array2d.var() #variance

987.64

In [68]:
array2d.squeeze()

array([[ 0.,  0., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [69]:
array2d.cumsum()

array([  0.,   0.,  45., 112., 146., 158., 236., 311., 401., 434.])

In [70]:
array2d.sum()

434.0

In [73]:
arr = array2d[0:,:3]

In [74]:
arr

array([[ 0.,  0., 45.],
       [12., 78., 75.]])

In [76]:
array2d[0:,2:]

array([[45., 67., 34.],
       [75., 90., 33.]])

#### Reshape()

In [77]:
array2d.reshape(5,2)

array([[ 0.,  0.],
       [45., 67.],
       [34., 12.],
       [78., 75.],
       [90., 33.]])

In [81]:
aa= array2d.flatten()
print(aa)  #it is just copy not will afftedt on the parrent array.

[ 0.  0. 45. 67. 34. 12. 78. 75. 90. 33.]


In [82]:
bb=array2d.ravel()
print(bb)#if we cange the anything inside the ravel then it will change automatically of array2d element.
#It is actualy the reference to the parent array and it is memory efficient.

[ 0.  0. 45. 67. 34. 12. 78. 75. 90. 33.]


In [83]:
#for an example:
bb[0]=1  #if we change the 0 index position value of the reval then it will affect on the main array.

In [84]:
array2d  #if we see the oth index position taken the value i.e.1.

array([[ 1.,  0., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

#### Sequences,repetitions and random numbers.

In [85]:
np.arange(1,10,dtype ='int')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [90]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [92]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [93]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
a =[1,2,3]

In [95]:
print(a)

[1, 2, 3]


In [96]:
np.tile(a,3)  #it is repeated the same list element three times.

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [97]:
np.repeat(a,3) #it is repeatating the one by one element of the list.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [98]:
np.repeat(array2d,3)

array([ 1.,  1.,  1.,  0.,  0.,  0., 45., 45., 45., 67., 67., 67., 34.,
       34., 34., 12., 12., 12., 78., 78., 78., 75., 75., 75., 90., 90.,
       90., 33., 33., 33.])

#### Random 

In [99]:
np.random.rand(3)  #it will gives us the dimensions.

array([0.27919725, 0.24025436, 0.73724932])

In [100]:
np.random.rand(3,3)

array([[0.06745237, 0.2375528 , 0.56718996],
       [0.6521476 , 0.64476953, 0.90109756],
       [0.91959317, 0.86181678, 0.19145437]])

In [101]:
np.random.randn(3,3)  #it will give us the uniformaly distributed random numbers

array([[ 0.37653252,  0.97454075, -0.82976096],
       [-1.42364852, -0.12908292,  0.14716561],
       [ 0.24563172, -2.3261353 ,  0.32553691]])

In [105]:
np.random.randint(0,10,size=[3,3]) #when we want the only int type of data randomly.

array([[0, 9, 2],
       [6, 4, 7],
       [1, 8, 7]])

In [107]:
np.random.randint(0,10,size=9).reshape(3,3)

array([[4, 7, 8],
       [8, 6, 3],
       [6, 9, 1]])

By the some we want to reproduce the random numbers that time use the seed function.

In [108]:
np.random.seed(0)
np.random.randint(1,10,[3,3])

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [109]:
np.random.seed(0)
np.random.randint(1,10,[3,3])  #it maintain the numbers if we cange the seed 1 then it will change the numbers.

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [111]:
np.random.seed(1)
np.random.randint(1,10,[3,3])#now it changed due to change in the seed.

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [112]:
np.unique(array2d) #return the unique numbers.

array([ 0.,  1., 12., 33., 34., 45., 67., 75., 78., 90.])

In [113]:
#if we want to known the count that time
unique,counts = np.unique(array2d,return_counts=True)

In [114]:
unique

array([ 0.,  1., 12., 33., 34., 45., 67., 75., 78., 90.])

In [115]:
counts

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Numpy 2nd Part.

In [116]:
arr = np.array([4,4,556,763,76,662,98,88,13])
arr

array([  4,   4, 556, 763,  76, 662,  98,  88,  13])

In [118]:
index_grt20 = np.where(arr>20)

In [119]:
index_grt20  #it will return the index postion.

(array([2, 3, 4, 5, 6, 7], dtype=int32),)

In [120]:
arr[index_grt10]#it will return the values.

array([556, 763,  76, 662,  98,  88])

In [121]:
arr>20

array([False, False,  True,  True,  True,  True,  True,  True, False])

In [122]:
np.where(arr>20,'gt20','lr20')  #those who are greater than 20 represented by 'gt20' if not then it represented by 'lr20'

array(['lr20', 'lr20', 'gt20', 'gt20', 'gt20', 'gt20', 'gt20', 'gt20',
       'lr20'], dtype='<U4')

In [125]:
arr.max()  #it will give us the maximum value directly.

763

In [126]:
arr.argmax()  #it wiil gives us the index position.

3

In [127]:
arr[arr.argmax()]

763

In [128]:
arr.argmin() #similarly

0

In [129]:
arr[arr.argmin()]

4

#### Import the text file 

In [137]:
data=np.genfromtxt('C:/Users/Microsoft/Desktop/pandas/ml-data-files/data.csv',delimiter=',',filling_values=-1000,dtype=float)

to turn off the scientific notation.

In [140]:
np.set_printoptions(suppress=True)
data[:3]

array([[-1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.        ,
        -1000.        , -1000.        , -1000.        , -1000.  

In [145]:
np.stack(array2d)

array([[ 1.,  0., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [146]:
np.hstack(array2d)

array([ 1.,  0., 45., 67., 34., 12., 78., 75., 90., 33.])

In [148]:
np.vstack(array2d)

array([[ 1.,  0., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [149]:
np.column_stack(array2d)

array([[ 1., 12.],
       [ 0., 78.],
       [45., 75.],
       [67., 90.],
       [34., 33.]])

In [150]:
np.row_stack(array2d)

array([[ 1.,  0., 45., 67., 34.],
       [12., 78., 75., 90., 33.]])

In [153]:
d =np.datetime64('2019-06-02 23:10:23')

In [154]:
d

numpy.datetime64('2019-06-02T23:10:23')

In [155]:
d+1000 #it will helps to add the seconds.

numpy.datetime64('2019-06-02T23:27:03')

In [156]:
oneday = np.timedelta64(1,'D')

In [157]:
oneday

numpy.timedelta64(1,'D')

In [158]:
oneday+1#It is helping to adding the day only.

numpy.timedelta64(2,'D')

In [159]:
oneminute = np.timedelta64(1,'m')
oneminute

numpy.timedelta64(1,'m')

In [160]:
oneminute+1#it is helping to add the one minute

numpy.timedelta64(2,'m')

In [162]:
dates= np.arange(np.datetime64('2019-06-02'),np.datetime64('2020-06-02'),2)
dates

array(['2019-06-02', '2019-06-04', '2019-06-06', '2019-06-08',
       '2019-06-10', '2019-06-12', '2019-06-14', '2019-06-16',
       '2019-06-18', '2019-06-20', '2019-06-22', '2019-06-24',
       '2019-06-26', '2019-06-28', '2019-06-30', '2019-07-02',
       '2019-07-04', '2019-07-06', '2019-07-08', '2019-07-10',
       '2019-07-12', '2019-07-14', '2019-07-16', '2019-07-18',
       '2019-07-20', '2019-07-22', '2019-07-24', '2019-07-26',
       '2019-07-28', '2019-07-30', '2019-08-01', '2019-08-03',
       '2019-08-05', '2019-08-07', '2019-08-09', '2019-08-11',
       '2019-08-13', '2019-08-15', '2019-08-17', '2019-08-19',
       '2019-08-21', '2019-08-23', '2019-08-25', '2019-08-27',
       '2019-08-29', '2019-08-31', '2019-09-02', '2019-09-04',
       '2019-09-06', '2019-09-08', '2019-09-10', '2019-09-12',
       '2019-09-14', '2019-09-16', '2019-09-18', '2019-09-20',
       '2019-09-22', '2019-09-24', '2019-09-26', '2019-09-28',
       '2019-09-30', '2019-10-02', '2019-10-04', '2019-