In [4]:
import numpy as np
list = [23,34,45]
array = np.array(list)
array

array([23, 34, 45])

In [5]:
import numpy as np
array_2d = [[23,34,67],[20,76,77],[11,34,98]]
print(array_2d)

[[23, 34, 67], [20, 76, 77], [11, 34, 98]]


In [7]:
arr = np.array(array_2d)
arr

array([[23, 34, 67],
       [20, 76, 77],
       [11, 34, 98]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(20,30,10)

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#random numbers

In [ ]:
#we want the uniformly ditributed numbers 

In [14]:
np.random.rand(2)

array([0.93795786, 0.12222213])

In [26]:
#normally distributed numbers
np.random.randn(3,3) # we will get the 3x3 matrix
np.random.randn(2)

array([-0.95693137, -1.04007666])

In [18]:
#if we want the interger type of random number that time we have to use the randin
np.random.randint(20,30)
#here we got the random number inbetween the 20 to 30

21

In [21]:
#in that way we can get the 10 numbers inbetween the 20 to 40 .
import numpy as np
np.random.randint(20,40,10)

array([32, 39, 26, 35, 36, 26, 28, 23, 21, 37])